# Generated by Django 4.1.5 on 2023-02-01 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 13, 22, 46, 751259, tzinfo=datetime.timezone.utc)),
        ),
    ]
