# Generated by Django 4.1.5 on 2023-02-02 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_certificate_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 15, 28, 8, 912070, tzinfo=datetime.timezone.utc)),
        ),
    ]
