# Generated by Django 4.1.5 on 2023-02-03 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_certificate_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 12, 26, 57, 679860, tzinfo=datetime.timezone.utc)),
        ),
    ]
