# Generated by Django 4.1.5 on 2023-02-08 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_certificate_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2023, 2, 8)),
        ),
    ]
